apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: backend
spec:
  containers:
    - name: mysql
      image: 510280374120.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment2:mysql-v0.1 
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD          # Root password for MySQL
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: MYSQL_DATABASE               # Initial database to create
          value: webapp_db
  imagePullSecrets:
    - name: ecr-secret