apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: web
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql
        app.kubernetes.io/component: backend
    spec:
      containers:
      - name: mysql
        image: 510280374120.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment1:mysql-v0.1
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: 3306