apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    app: employees
spec:
  imagePullSecrets:
    - name: ecr-secret
  containers:
    - name: webapp
      image: 510280374120.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment2:webapp-v0.1
      ports:
        - containerPort: 80
      env:
        - name: DBHOST
          value: "mysql.web.svc.cluster.local"
        - name: DBPORT
          value: "3306"
