apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      serviceAccountName: clo835-group2
      containers:
        - name: webapp
          image: 510280374120.dkr.ecr.us-east-1.amazonaws.com/clo835-project:webapp-v0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 81
          env:
            - name: DBUSER
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql-user
            - name: DBPWD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql-password

            - name: DBHOST
              valueFrom:
                configMapKeyRef:
                  name: variables
                  key: DBHOST
            - name: DBPORT
              valueFrom:
                configMapKeyRef:
                  name: variables
                  key: DBPORT
            - name: MY_NAME
              valueFrom:
                configMapKeyRef:
                  name: variables
                  key: MY_NAME
            - name: BACKGROUND_IMAGE
              valueFrom:
                configMapKeyRef:
                  name: variables
                  key: BACKGROUND_IMAGE
            - name: APP_COLOR
              valueFrom:
                configMapKeyRef:
                  name: variables
                  key: APP_COLOR