apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: final
type: Opaque
data:
  mysql-root-password: cHc=== # pw encoded into base64
  mysql-user: cm9vdA==        # root encoded base64
  